-- Next Query: Payment preeferences
-- Goal: Understand the most popular payment methods and 
-- how they correlate with other customer behaviors

-- Count of Orders by Payment Type:
-- this will show the most popular payment types in terms of order count
SELECT payment_type, COUNT(*) AS order_count
FROM payments
GROUP BY 1
ORDER BY order_count DESC;

-- Average payment value by payment type 
-- this will help you understand which payment method is associated with higher spending
SELECT	payment_type, AVG(payment_value) as average_payment_value
FROM	payments
GROUP BY	1
ORDER BY 	average_payment_value DESC;

-- Total Payment Value by Payment Type
-- this will show how much revenue is generated by each payment type
SELECT	payment_type, SUM(payment_value) as total_payment_value
FROM	payments
GROUP BY	1
ORDER BY	total_payment_value DESC;

-- Payment Preferences by Region:
-- This will give insights into regional preferences for payment methods by joining
-- the payments table with the customers table based on customer_id
SELECT	c.customer_state,
		SUM(CASE WHEN p.payment_type = 'wallet' THEN 1 ELSE 0 END) as through_wallet,
        SUM(CASE WHEN p.payment_type = 'voucher' THEN 1 ELSE 0 END) as through_voucher,
        SUM(CASE WHEN p.payment_type = 'debit_card' THEN 1 ELSE 0 END) as through_debit_card,
        SUM(CASE WHEN p.payment_type = 'credit_card' THEN 1 ELSE 0 END) as through_credit_card,
        COUNT(*) as payment_count
        
FROM	payments p 
JOIN	orders o
		ON p.order_id = o.order_id
JOIN	customers c
		ON o.customer_id = c.customer_id        
GROUP BY 1
ORDER BY payment_count DESC;

-- Payment preferences by spending level (e.g., High vs Low Spend)
-- this can help identify if customers who spend more tend to prefer certain payment methods
WITH
	spend_level as (
    SELECT
	CASE
		WHEN 	payment_value >= 500 THEN 'High Spend'
        ELSE	'Low Spend'
	END as spend_level,
    payment_type,
    COUNT(*) as order_count
FROM	payments
GROUP BY	spend_level, payment_type
)
SELECT
	payment_type,
	SUM(CASE WHEN spend_level = 'High Spend' THEN order_count ELSE 0 END) as high_spend_count,
    SUM(CASE WHEN spend_level = 'Low Spend' THEN order_count ELSE 0 END) as low_spend_count
FROM	spend_level
GROUP BY	payment_type;

-- Payment Preferences over time
-- This will show if there are any trends in payment preferences over different months
SELECT
	DATE_FORMAT(o.order_purchase_timestamp, '%Y-%m') as month,
    SUM(CASE WHEN p.payment_type = 'wallet' THEN 1 ELSE 0 END) as through_wallet,
	SUM(CASE WHEN p.payment_type = 'voucher' THEN 1 ELSE 0 END) as through_voucher,
    SUM(CASE WHEN p.payment_type = 'debit_card' THEN 1 ELSE 0 END) as through_debit_card,
    SUM(CASE WHEN p.payment_type = 'credit_card' THEN 1 ELSE 0 END) as through_credit_card,
    COUNT(*) as order_count
FROM	payments p
JOIN	orders o
		ON p.order_id = o.order_id
GROUP BY	month
HAVING month != '2016-12' AND month != '2016-09' #excluding incomplete data from dataset
ORDER BY	1;
